apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
      k8s-app: jupyterlab
      owner: {{username}}
  name: {{username}}-cephfs-pvc
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs